"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import AnalyticsDashboard from "@/components/dashboard/AnalyticsDashboard";
import TelemetryChart from "@/components/dashboard/TelemetryChart";
import type { AnalyticsReading, PredictionApiResponse, Tank } from "@/components/dashboard/types";
import { getAnalytics, getOverflowPredictions, getTanks } from "@/services/api";
import { ModuleError, ModuleLoading, ModuleScaffold } from "./ModuleScaffold";
import { useApiSession } from "./useApiSession";

const average=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0;
export default function AnalyticsPageClient(){const session=useApiSession();const[tanks,setTanks]=useState<Tank[]>([]);const[all,setAll]=useState<AnalyticsReading[]>([]);const[predictions,setPredictions]=useState<PredictionApiResponse[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const t=await getTanks();setTanks(t);const [analytics,predictionData]=await Promise.all([t.length?getAnalytics(t.map(x=>x.id),"all",true):null,getOverflowPredictions()]);setAll(analytics?.readings??[]);setPredictions(predictionData);}catch{setError("Analytics data could not be loaded from the monitoring API.");}finally{setLoading(false);}},[]);useEffect(()=>{const id=window.setTimeout(()=>{if(session)void load();else if(session===false)setLoading(false)},0);return()=>window.clearTimeout(id)},[session,load]);
 const aggregates=useMemo(()=>{const group=(unit:"day"|"week"|"month")=>{const map=new Map<string,number[]>();all.forEach(r=>{if(r.level==null)return;const d=new Date(r.recorded_at);if(Number.isNaN(d.getTime()))return;let bucket:Date;if(unit==="month")bucket=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1));else if(unit==="week"){bucket=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));const day=bucket.getUTCDay()||7;bucket.setUTCDate(bucket.getUTCDate()-day+1)}else bucket=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));const key=bucket.toISOString();(map.get(key)??map.set(key,[]).get(key)!).push(r.level);});return[...map].sort(([a],[b])=>a.localeCompare(b)).map(([recorded_at,v])=>({recorded_at,level:Number(average(v).toFixed(2))}));};return{daily:group("day"),weekly:group("week"),monthly:group("month")};},[all]);
 const recent=aggregates.daily.slice(-7);const trend=recent.length>1?recent.at(-1)!.level-recent[0]!.level:0;
 return <ModuleScaffold eyebrow="Network intelligence" title="Analytics" description="Compare telemetry, inspect aggregated operating patterns and review trend direction using recorded API data.">{loading?<ModuleLoading/>:error?<ModuleError message={error} retry={()=>void load()}/>:<div className="space-y-6"><AnalyticsDashboard tanks={tanks}/><div className="grid gap-5 xl:grid-cols-3">{([['Daily averages',aggregates.daily],['Weekly averages',aggregates.weekly],['Monthly averages',aggregates.monthly]] as const).map(([title,data])=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">{title}</h2><p className="mb-4 text-xs text-slate-500">Network-wide sewage fill</p>{data.length?<TelemetryChart data={data} unit="%" height={230} series={[{key:"level",name:title,color:"#0891b2"}]}/>:<p className="grid h-52 place-items-center text-sm text-slate-500">No readings available for this interval.</p>}</article>)}</div><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">AI overflow prediction chart</h2><p className="text-xs text-slate-500">Current API risk score by tank</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{predictions.map(p=>{const name=tanks.find(t=>t.id===p.tank_id)?.tank_name??p.tank_id;return <div key={p.tank_id}><div className="flex justify-between text-xs"><span className="font-semibold">{name}</span><span>{p.risk.toFixed(0)}%</span></div><div className="mt-1 h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full ${p.risk>=90?"bg-red-600":p.risk>=60?"bg-amber-500":"bg-cyan-600"}`} style={{width:`${Math.max(0,Math.min(100,p.risk))}%`}}/></div></div>})}{!predictions.length&&<p className="text-sm text-slate-500">No prediction results are available.</p>}</div></section><article className="rounded-2xl border border-cyan-100 bg-cyan-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Trend analysis</p><div className="mt-3 flex flex-wrap items-end gap-5"><p className="text-4xl font-black">{trend>=0?"+":""}{trend.toFixed(1)}%</p><p className="max-w-2xl text-sm text-cyan-50">Change in network daily average across the latest available seven-day window. {trend>3?"The rising trend warrants earlier collection planning.":trend< -3?"Average fill is declining following collection activity.":"The network is broadly stable."}</p></div></article></div>}</ModuleScaffold>}
