"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getLatestReadings, getTanks } from "@/services/api";
import type { SensorReading, Tank } from "@/components/dashboard/types";
import { ModuleError, ModuleLoading, ModuleScaffold } from "./ModuleScaffold";
import { useApiSession } from "./useApiSession";

const condition = (reading?: SensorReading) => !reading ? "OFFLINE" : (reading.level ?? 0) >= 95 || (reading.gas_level ?? 0) >= 300 ? "CRITICAL" : (reading.level ?? 0) >= 80 || (reading.gas_level ?? 0) >= 200 ? "WARNING" : "SAFE";
const tones = { SAFE: "bg-emerald-50 text-emerald-700", WARNING: "bg-amber-50 text-amber-700", CRITICAL: "bg-red-50 text-red-700", OFFLINE: "bg-slate-100 text-slate-600" };

export default function TanksPageClient() {
  const session = useApiSession(); const [tanks,setTanks]=useState<Tank[]>([]); const [readings,setReadings]=useState<SensorReading[]>([]); const [query,setQuery]=useState(""); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const t=await getTanks();setTanks(t);const r=await getLatestReadings().catch(()=>[]);setReadings(r);}catch{setError("Unable to load the tank registry and live telemetry.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const id=window.setTimeout(()=>{if(session)void load();else if(session===false)setLoading(false)},0);return()=>window.clearTimeout(id)},[session,load]);
  const byTank=useMemo(()=>new Map(readings.map(r=>[r.tank_id,r])),[readings]);
  const visible=tanks.filter(t=>[t.tank_name,t.location,t.owner_name,String(t.thingspeak_channel_id??"")].some(v=>v.toLowerCase().includes(query.toLowerCase())));
  return <ModuleScaffold eyebrow="Asset registry" title="Tanks Management" description="Live operating condition, device assignment and ownership for every registered sewer tank." actions={<Link href="/map" className="rounded-lg bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950">Open GIS map</Link>}>
    {loading?<ModuleLoading/>:error?<ModuleError message={error} retry={()=>void load()}/>:<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">Registered tanks</h2><p className="text-sm text-slate-500">{visible.length} of {tanks.length} assets</p></div><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search tanks" placeholder="Search tank, location, owner or channel" className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-cyan-600 sm:w-80"/></div><div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Tank","Status","Fill","Gas","Location","Assigned device","Last communication","ThingSpeak","Capacity","Owner","Actions"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map(t=>{const r=byTank.get(t.id);const state=condition(r);return <tr key={t.id} className="hover:bg-cyan-50/40"><td className="px-4 py-4 font-bold text-slate-900">{t.tank_name}</td><td className="px-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${tones[state]}`}>{state}</span></td><td className="px-4 font-semibold">{r?.level==null?"—":`${r.level.toFixed(1)}%`}</td><td className="px-4">{r?.gas_level==null?"—":`${r.gas_level.toFixed(0)} ppm`}</td><td className="px-4 text-slate-600">{t.location}</td><td className="px-4 font-mono text-xs">{r?.device_reading_id?`ESP32 · ${r.device_reading_id.slice(0,8)}`:"ThingSpeak feed"}</td><td className="px-4 whitespace-nowrap text-slate-600">{r?new Date(r.recorded_at).toLocaleString("en-UG"):"Never"}</td><td className="px-4">{t.thingspeak_channel_id??"—"}</td><td className="px-4 whitespace-nowrap">{t.capacity_liters.toLocaleString()} L</td><td className="px-4 text-slate-600">{t.owner_name}</td><td className="px-4"><div className="flex gap-2"><Link href={`/tanks/${t.id}`} className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Details</Link><Link href={`/map?tank=${t.id}`} className="rounded-lg border border-cyan-300 px-3 py-2 text-xs font-bold text-cyan-800">Map</Link></div></td></tr>})}{visible.length===0&&<tr><td colSpan={11} className="p-12 text-center text-slate-500">No tanks match the current search.</td></tr>}</tbody></table></div></section>}
  </ModuleScaffold>;
}
