"use client";

import type { ReportJob } from "./types";

interface Props {
  jobs: ReportJob[];
  loading: boolean;
  onDownload: (job: ReportJob) => void;
  onShare: (job: ReportJob) => void;
  onDelete: (job: ReportJob) => void;
}

const formatTone = { PDF: "bg-red-50 text-red-700", CSV: "bg-emerald-50 text-emerald-700", Excel: "bg-cyan-50 text-cyan-700" };
const statusTone = { Ready: "bg-emerald-50 text-emerald-700", Processing: "bg-amber-50 text-amber-700", Failed: "bg-red-50 text-red-700" };

export default function RecentReportsTable({ jobs, loading, onDownload, onShare, onDelete }: Props) {
  return (
    <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
      <header className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold text-slate-900">Recently Generated Reports</h2><p className="mt-1 text-xs text-slate-500">Latest report jobs generated from operational records.</p></header>
      {loading ? <div className="space-y-3 p-5">{[1, 2, 3].map((key) => <div key={key} className="h-12 animate-pulse rounded-lg bg-slate-100" />)}</div> :
        jobs.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm">
          <thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-600"><tr>
            <th className="px-5 py-3 font-semibold">Report Name</th><th className="px-5 py-3 font-semibold">Date Generated</th>
            <th className="px-5 py-3 font-semibold">Format</th><th className="px-5 py-3 font-semibold">Generated By</th>
            <th className="px-5 py-3 font-semibold">Status</th><th className="px-5 py-3 text-right font-semibold">Actions</th>
          </tr></thead>
          <tbody className="divide-y divide-slate-200">{jobs.map((job) => <tr key={job.id} className="hover:bg-slate-50">
            <td className="max-w-sm truncate px-5 py-4 font-semibold text-slate-900" title={job.fileName}>{job.fileName}</td>
            <td className="px-5 py-4 text-slate-600">{new Date(job.generatedAt).toLocaleDateString("en-GB")}</td>
            <td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${formatTone[job.format]}`}>{job.format}</span></td>
            <td className="px-5 py-4 text-slate-600">{job.generatedBy}</td>
            <td className="px-5 py-4"><span title={job.error} className={`rounded-full px-2.5 py-1 text-xs font-bold ${statusTone[job.status]}`}>{job.status}</span></td>
            <td className="px-5 py-4"><div className="flex justify-end gap-2">
              <button type="button" disabled={job.status !== "Ready"} onClick={() => onDownload(job)} className="h-8 rounded-md border border-slate-300 px-3 text-xs font-bold text-slate-700 hover:bg-slate-100 disabled:opacity-40">Download</button>
              <button type="button" disabled={job.status !== "Ready"} onClick={() => onShare(job)} title={`Share ${job.fileName}`} aria-label={`Share ${job.fileName}`} className="h-8 w-8 rounded-md border border-slate-300 text-slate-600 hover:bg-slate-100 disabled:opacity-40">↗</button>
              <button type="button" onClick={() => onDelete(job)} title={`Delete ${job.fileName}`} className="h-8 rounded-md px-2 text-xs font-bold text-red-700 hover:bg-red-50">Delete</button>
            </div></td>
          </tr>)}</tbody>
        </table></div> :
        <div className="px-5 py-14 text-center"><p className="font-semibold text-slate-700">No reports generated yet</p><p className="mt-1 text-sm text-slate-500">Use the filters or a standard template to create the first report.</p></div>}
    </section>
  );
}

