import type { OptimizedRoute } from "./types";

const priorityStyle = { CRITICAL: "bg-red-100 text-red-700", HIGH: "bg-orange-100 text-orange-700", MEDIUM: "bg-yellow-100 text-yellow-700" } as const;
const duration = (minutes: number) => minutes >= 60 ? `${Math.floor(minutes / 60)}h ${minutes % 60}m` : `${minutes} min`;

export default function OptimizedRoutePanel({ route }: { route: OptimizedRoute | null }) {
  const metrics = route ? [{ label: "Distance", value: `${route.totalDistanceKm.toFixed(1)} km` }, { label: "Duration", value: duration(route.estimatedDurationMinutes) }, { label: "Tanks", value: route.tankCount }, { label: "Priority", value: `${route.priorityScore}/100` }] : [];
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-700">Collection intelligence</p><h2 className="mt-1 text-lg font-semibold text-slate-900">Optimized truck route</h2><p className="mt-1 text-sm text-slate-500">Critical-first collection order with distance optimization.</p></div>
    {route && <div className="mt-4 grid grid-cols-2 gap-px overflow-hidden rounded-xl bg-slate-200 sm:grid-cols-4">{metrics.map((metric) => <div key={metric.label} className="bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{metric.label}</p><p className="mt-1 text-lg font-extrabold text-slate-900">{metric.value}</p></div>)}</div>}
    {!route || route.stops.length === 0 ? <p className="mt-6 text-sm text-slate-500">No tanks currently meet collection or open-work criteria.</p> : <ol className="mt-5 space-y-3">{route.stops.map((stop) => <li key={stop.tankId} className="flex gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-cyan-700 text-xs font-bold text-white">{stop.sequence}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="font-semibold text-slate-900">{stop.tankName}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${priorityStyle[stop.priority]}`}>{stop.priority}</span></div><p className="truncate text-xs text-slate-500">{stop.location} · {stop.distanceFromPreviousKm.toFixed(1)} km from previous</p><p className="mt-1 text-xs font-medium text-slate-700">{stop.task}{stop.fillLevel != null ? ` · ${stop.fillLevel.toFixed(0)}% full` : ""}</p></div></li>)}</ol>}
  </section>;
}
