import Link from "next/link";
import AnimatedValue from "@/components/ui/AnimatedValue";
import type { SensorReading, Tank } from "./types";
import { isLiveReading } from "./telemetry";

interface Props { tank: Tank; reading: SensorReading | null; }
const configuredGasThreshold = Number(process.env.NEXT_PUBLIC_GAS_LEVEL_THRESHOLD ?? 300);
const gasThreshold = Number.isFinite(configuredGasThreshold) ? configuredGasThreshold : 300;
export default function TankStatusCard({ tank, reading }: Props) {
  const level = reading?.level; const live = isLiveReading(reading); const hazardousGas = reading?.gas_level != null && reading.gas_level >= gasThreshold; const critical = hazardousGas || (level != null && level >= 95); const warning = !critical && level != null && level >= 80;
  const status = !live ? { label: "Offline", badge: "bg-slate-100 text-slate-700", dot: "bg-slate-400", bar: "bg-slate-400" } : critical ? { label: "Critical", badge: "bg-rose-100 text-rose-800", dot: "bg-rose-500", bar: "bg-rose-600" } : warning ? { label: "Warning", badge: "bg-amber-100 text-amber-800", dot: "bg-amber-500", bar: "bg-amber-500" } : { label: "Normal", badge: "bg-emerald-100 text-emerald-800", dot: "bg-emerald-500", bar: "bg-emerald-500" };
  return <Link href={`/tanks/${encodeURIComponent(tank.id)}`} className="ui-interactive-card block h-full rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{tank.tank_name}</h3><p className="mt-1 text-sm text-slate-500">{tank.location}</p></div><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${status.badge}`}><span className={`size-1.5 rounded-full ${status.dot}`}/>{status.label}</span></div><div className="mt-5 flex items-end justify-between"><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Fill level</p><p className="mt-1 text-3xl font-bold text-slate-950">{level == null ? "—" : <AnimatedValue value={level} decimals={1} suffix="%"/>}</p></div><p className="text-right text-xs text-slate-500">Capacity<br/><span className="font-semibold text-slate-700">{tank.capacity_liters.toLocaleString()} L</span></p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full transition-[width] duration-300 ${status.bar}`} style={{ width: `${Math.max(0, Math.min(level ?? 0, 100))}%` }}/></div><p className="mt-3 text-xs text-slate-500">{reading ? `Last telemetry: ${new Date(reading.recorded_at).toLocaleString()}` : "No live telemetry received yet."}</p><p className="mt-3 text-xs font-bold text-cyan-700">Open tank details →</p></Link>;
}
