import type { SensorReading, Tank } from "./types";

interface Props { tanks: Tank[]; reading: SensorReading | null; query: string; onQueryChange: (query: string) => void; onSelect: (tankId: string) => void; }

export default function TankMonitoringTable({ tanks, reading, query, onQueryChange, onSelect }: Props) {
  const normalized = query.trim().toLowerCase();
  const visibleTanks = tanks.filter((tank) => !normalized || [tank.tank_name, tank.location, tank.owner_name].some((value) => value.toLowerCase().includes(normalized)));
  return (
    <section id="tanks" className="scroll-mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex flex-col gap-4 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Live tank monitoring</h2><p className="mt-1 text-sm text-slate-500">Search and select a tank to inspect its recorded trend.</p></div><label className="relative block sm:w-72"><span className="sr-only">Search tanks</span><span aria-hidden="true" className="absolute left-3 top-2.5 text-slate-400">⌕</span><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search tank or location" className="w-full rounded-lg border border-slate-300 bg-slate-50 py-2 pl-9 pr-3 text-sm text-slate-900 outline-none transition focus:border-cyan-600 focus:bg-white focus:ring-2 focus:ring-cyan-100" /></label></div>
      <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-semibold">Tank</th><th className="px-5 py-3 font-semibold">Location</th><th className="px-5 py-3 font-semibold">Fill level</th><th className="px-5 py-3 font-semibold">Device status</th><th className="px-5 py-3 font-semibold"><span className="sr-only">Action</span></th></tr></thead><tbody className="divide-y divide-slate-100">{visibleTanks.length === 0 ? <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">{tanks.length === 0 ? "No tanks are registered yet." : "No tanks match your search."}</td></tr> : visibleTanks.map((tank) => { const tankReading = reading?.tank_id === tank.id ? reading : null; return <tr key={tank.id} className="transition hover:bg-cyan-50/50"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{tank.tank_name}</p><p className="mt-0.5 text-xs text-slate-500">{tank.capacity_liters.toLocaleString()} L capacity</p></td><td className="px-5 py-4 text-slate-600">{tank.location}</td><td className="px-5 py-4 font-semibold text-slate-900">{tankReading?.level == null ? "—" : `${tankReading.level.toFixed(1)}%`}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${tankReading ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}><span className={`size-1.5 rounded-full ${tankReading ? "bg-emerald-500" : "bg-slate-400"}`} />{tankReading ? "Reporting" : "Awaiting data"}</span></td><td className="px-5 py-4 text-right"><button type="button" onClick={() => onSelect(tank.id)} className="font-semibold text-cyan-700 hover:text-cyan-900">View trend</button></td></tr>; })}</tbody></table></div>
    </section>
  );
}
