export type TankStatus = "ACTIVE" | "INACTIVE" | "MAINTENANCE";
export interface Tank { id: string; tank_name: string; owner_name: string; owner_user_id?: string | null; location: string; latitude: number; longitude: number; capacity_liters: number; status: TankStatus; thingspeak_channel_id?: number; thingspeak_read_api_key?: string; created_at: string; updated_at: string; }
export interface SensorReading { id: string; tank_id: string; thingspeak_channel_id: number | null; thingspeak_entry_id: number | null; device_reading_id?: string | null; level: number | null; gas_level: number | null; status?: "SAFE" | "WARNING" | "CRITICAL" | null; recorded_at: string; created_at: string; }
export interface HistoricalSensorReading { recorded_at: string; level: number | null; gas_level: number | null; }
export type AnalyticsRange = "1h" | "24h" | "7d" | "30d" | "all";
export interface AnalyticsReading extends HistoricalSensorReading { tank_id: string; }
export interface AnalyticsSummary { highestFill: number | null; averageFill: number | null; highestGas: number | null; reportingDeviceCount: number; offlineDeviceCount: number; }
export interface AnalyticsResponse { range: AnalyticsRange; generatedAt: string; readings: AnalyticsReading[]; summary: AnalyticsSummary; }
export interface DashboardSummary { totalTanks: number; onlineTanks: number; activeAlerts: number; averageFillLevel: number; }
export interface AlertItem { id: string; tank_id: string; tank_name: string; location: string; latitude: number; longitude: number; alert_type: string; severity: "critical" | "warning" | "info"; status: "ACTIVE" | "ACKNOWLEDGED" | "RESOLVED"; message: string; created_at: string; updated_at: string; last_seen_at: string; acknowledged_by: string | null; acknowledged_by_name: string | null; acknowledged_at: string | null; resolved_at: string | null; }
export type MaintenanceStatus = "SCHEDULED" | "ASSIGNED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
export type MaintenancePriority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export interface MaintenanceItem { id: string; tank_id: string; tank_name: string; task: string; scheduled_for: string; status: MaintenanceStatus; priority: MaintenancePriority; assigned_to: string | null; assigned_officer: string | null; completed_at: string | null; notes: string | null; created_at: string; }
export interface MaintenanceOfficer { id: string; full_name: string; email: string; role: "MAINTENANCE_OFFICER"; }
export type PredictionStatus = "PROJECTED" | "THRESHOLD_REACHED" | "STABLE_OR_FALLING" | "INSUFFICIENT_DATA";
export interface ThresholdProjection { thresholdPercent: 65 | 85 | 100; estimatedArrivalAt: string | null; remainingHours: number | null; status: PredictionStatus; }
export interface OverflowPrediction { tankId: string; currentLevel: number | null; fillVelocityPercentPerHour: number; historicalAverageDailyIncrease: number; diagnosticEndpointRatePercentPerHour: number; remainingCapacityPercent: number | null; remainingCapacityCubicMeters: number | null; warningProjection: ThresholdProjection; dangerProjection: ThresholdProjection; overflowProjection: ThresholdProjection; recommendedMaintenanceAt: string | null; risk: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; riskPercentage: number; confidence: number; samples: number; generatedAt: string; }
export interface PredictionApiResponse { tank_id: string; current_level: number | null; fill_velocity_percent_per_hour: number; historical_average_daily_increase: number; remaining_capacity_percent: number | null; remaining_capacity_cubic_meters: number | null; warning_projection: ThresholdProjection; danger_projection: ThresholdProjection; overflow_projection: ThresholdProjection; risk: number; risk_level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; confidence: number; recommended_maintenance_date: string | null; samples: number; generated_at: string; }
export interface UrgencyFactor { label: string; points: number; detail: string; }
export interface RouteTankStop { stopType: "TANK"; tankId: string; tankName: string; location: string; latitude: number; longitude: number; task: string; scheduledFor: string; fillLevel: number | null; capacityLiters: number; estimatedCollectionLiters: number; priority: "CRITICAL" | "HIGH" | "MEDIUM"; priorityScore: number; urgencyFactors: UrgencyFactor[]; sequence: number; distanceFromPreviousKm: number; drivingMinutesFromPrevious: number; payloadAfterLiters: number; locked: boolean; assignedTo: string | null; assignedOfficer: string | null; }
export interface RouteFacilityStop { stopType: "DISPOSAL" | "DEPOT_RETURN"; sequence: number; name: string; latitude: number; longitude: number; distanceFromPreviousKm: number; drivingMinutesFromPrevious: number; payloadBeforeLiters: number; payloadAfterLiters: number; }
export type OptimizedRouteStop = RouteTankStop | RouteFacilityStop;
export interface RouteOptimizationRequest { truckId?: string; driverId?: string; truckCapacityLiters?: number; shiftDurationMinutes?: number; excludedTankIds?: string[]; preferredOrder?: string[]; lockedTankIds?: string[]; }
export interface OptimizedRoute { depot: { latitude: number; longitude: number }; disposalSite: { name: string; latitude: number; longitude: number }; stops: OptimizedRouteStop[]; roadGeometry: Array<[number,number]>; totalDistanceKm: number; totalDrivingMinutes: number; totalServiceMinutes: number; totalUnloadingMinutes: number; estimatedDurationMinutes: number; tankCount: number; disposalTrips: number; truckCapacityLiters: number; selectedTruckId: string; selectedDriverId: string | null; availableDrivers: Array<{id:string;name:string}>; shiftDurationMinutes: number; exceedsShift: boolean; deferredTankIds: string[]; priorityScore: number; routingSource: "OSRM" | "FALLBACK"; fallbackReason: string | null; generatedAt: string; }
export type NotificationStatus = "PENDING" | "SENT" | "FAILED";
export interface NotificationItem { id: string; alert_id: string; user_id: string; channel: "EMAIL" | "IN_APP" | "SMS_DEVICE" | "SMS_CLOUD"; status: NotificationStatus; recipient: string; subject: string; message: string; sent_at: string | null; read_at: string | null; error_message: string | null; created_at: string; tank_id: string; tank_name: string; severity: "critical" | "warning" | "info"; alert_type: string; }
export interface NotificationPreferences { id: string; user_id: string; email_enabled: boolean; sms_enabled: boolean; in_app_enabled: boolean; critical_only: boolean; warning_enabled: boolean; daily_summary: boolean; created_at: string; updated_at: string; }
